version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: app
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: ecommerce_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
